language: java
jdk: openjdk12
sudo: required
services:
  - docker
cache:
  directories:
    - "$HOME/.m2/repository"

env:
  global:
    - TAG=latest
    - IMAGE_NAME=$REGISTRY_HOSTNAME/$PROJECT_NAME

install: true

script:
  - mvn package -U -B -P prod,coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
